// <auto-generated />
using System;
using Gw2Gizmos.Data.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gw2Gizmos.Data.Provider.Sqlite.Migrations
{
    [DbContext(typeof(Gw2GizmosDbContext))]
    [Migration("20260611184701_AddNotification")]
    partial class AddNotification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Commerce.BuyListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommerceItemListingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Listings")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommerceItemListingId");

                    b.ToTable("BuyListings");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Commerce.CommerceItemListing", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("CommerceItemListings");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Commerce.SellListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommerceItemListingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Listings")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommerceItemListingId");

                    b.ToTable("SellListings");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Currencies.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ArmorDetails", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AttributeAdjustment")
                        .HasColumnType("TEXT");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SecondarySuffixItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SuffixItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WeightClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.ToTable("ArmorDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ArmorStatChoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmorDetailsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ArmorDetailsId");

                    b.ToTable("ArmorStatChoices");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.BackItemDetails", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AttributeAdjustment")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SecondarySuffixItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SuffixItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("BackItemDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.BackItemStatChoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackItemDetailsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BackItemDetailsId");

                    b.ToTable("BackItemStatChoices");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.BagDetails", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NoSellOrSort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("BagDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ConsumableDetails", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApplyCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ColorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GuildUpgradeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnlockType")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.ToTable("ConsumableDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ConsumableExtraRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsumableId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConsumableId");

                    b.ToTable("ConsumableExtraRecipes");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ConsumableSkin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsumableId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkinId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConsumableId");

                    b.ToTable("ConsumableSkins");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ContainerDetails", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.ToTable("ContainerDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.GatheringDetails", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.ToTable("GatheringDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.InfixUpgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InfixUpgrade");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.InfixUpgradeAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attribute")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InfixUpgradeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Modifier")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InfixUpgradeId");

                    b.ToTable("InfixUpgradeAttributes");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.InfixUpgradeBuff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("InfixUpgradeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InfixUpgradeId")
                        .IsUnique();

                    b.ToTable("InfixUpgradeBuffs");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChatLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DefaultSkin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VendorValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ItemFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemFlags");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ItemGameType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemGameTypes");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ItemInfusionSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ItemInfusionSlot");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ItemInfusionSlotFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InfusionSlotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InfusionSlotId");

                    b.ToTable("ItemInfusionSlotFlags");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ItemRestriction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemRestrictions");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.MiniPetDetails", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinipetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("MiniPetDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ToolDetails", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Charges")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.ToTable("ToolDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.TrinketDetails", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AttributeAdjustment")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SecondarySuffixItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SuffixItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.ToTable("TrinketDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.TrinketStatChoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrinketDetailsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrinketDetailsId");

                    b.ToTable("TrinketStatChoices");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.UpgradeComponentDetails", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Bonuses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Flags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("InfusionUpgradeFlags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Suffix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.ToTable("UpgradeComponentDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.WeaponDetails", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AttributeAdjustment")
                        .HasColumnType("TEXT");

                    b.Property<string>("DamageType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPower")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinPower")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SecondarySuffixItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SuffixItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.ToTable("WeaponDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.WeaponStatChoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeaponDetailsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WeaponDetailsId");

                    b.ToTable("WeaponStatChoices");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Notifications.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Recipes.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChatLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MinRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutputItemCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutputItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OutputUpgradeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeToCraftMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Recipes.RecipeDiscipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeDisciplines");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Recipes.RecipeFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeFlags");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Recipes.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.State.AppState", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppState");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ArmorInfixUpgrade", b =>
                {
                    b.HasBaseType("Gw2Gizmos.Data.EntityFramework.Entities.Items.InfixUpgrade");

                    b.Property<int>("ArmorDetailsId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ArmorDetailsId")
                        .IsUnique();

                    b.ToTable("ArmorInfixUpgrades");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.BackItemInfixUpgrade", b =>
                {
                    b.HasBaseType("Gw2Gizmos.Data.EntityFramework.Entities.Items.InfixUpgrade");

                    b.Property<int>("BackItemDetailsId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("BackItemDetailsId")
                        .IsUnique();

                    b.ToTable("BackItemInfixUpgrades");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.TrinketInfixUpgrade", b =>
                {
                    b.HasBaseType("Gw2Gizmos.Data.EntityFramework.Entities.Items.InfixUpgrade");

                    b.Property<int>("TrinketDetailsId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("TrinketDetailsId")
                        .IsUnique();

                    b.ToTable("TrinketInfixUpgrades");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.UpgradeComponentInfixUpgrade", b =>
                {
                    b.HasBaseType("Gw2Gizmos.Data.EntityFramework.Entities.Items.InfixUpgrade");

                    b.Property<int>("UpgradeComponentDetailsId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("UpgradeComponentDetailsId")
                        .IsUnique();

                    b.ToTable("UpgradeComponentInfixUpgrades");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.WeaponInfixUpgrade", b =>
                {
                    b.HasBaseType("Gw2Gizmos.Data.EntityFramework.Entities.Items.InfixUpgrade");

                    b.Property<int>("WeaponDetailsId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("WeaponDetailsId")
                        .IsUnique();

                    b.ToTable("WeaponInfixUpgrades");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Armor", b =>
                {
                    b.HasBaseType("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item");

                    b.ToTable("Armors");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.BackItem", b =>
                {
                    b.HasBaseType("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item");

                    b.ToTable("BackItems");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Bag", b =>
                {
                    b.HasBaseType("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item");

                    b.ToTable("Bags");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Consumable", b =>
                {
                    b.HasBaseType("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item");

                    b.ToTable("Consumables");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Container", b =>
                {
                    b.HasBaseType("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item");

                    b.ToTable("Containers");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Gathering", b =>
                {
                    b.HasBaseType("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item");

                    b.ToTable("Gatherings");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Gizmo", b =>
                {
                    b.HasBaseType("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item");

                    b.ToTable("Gizmos");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.MiniPet", b =>
                {
                    b.HasBaseType("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item");

                    b.ToTable("MiniPets");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Tool", b =>
                {
                    b.HasBaseType("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Trinket", b =>
                {
                    b.HasBaseType("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item");

                    b.ToTable("Trinkets");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.UpgradeComponent", b =>
                {
                    b.HasBaseType("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item");

                    b.ToTable("UpgradeComponents");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Weapon", b =>
                {
                    b.HasBaseType("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ArmorInfusionSlot", b =>
                {
                    b.HasBaseType("Gw2Gizmos.Data.EntityFramework.Entities.Items.ItemInfusionSlot");

                    b.Property<int>("ArmorDetailsId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ArmorDetailsId");

                    b.ToTable("ArmorInfusionSlots");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.BackItemInfusionSlot", b =>
                {
                    b.HasBaseType("Gw2Gizmos.Data.EntityFramework.Entities.Items.ItemInfusionSlot");

                    b.Property<int>("BackItemDetailsId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("BackItemDetailsId");

                    b.ToTable("BackItemInfusionSlots");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.TrinketInfusionSlot", b =>
                {
                    b.HasBaseType("Gw2Gizmos.Data.EntityFramework.Entities.Items.ItemInfusionSlot");

                    b.Property<int>("TrinketDetailsId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("TrinketDetailsId");

                    b.ToTable("TrinketInfusionSlots");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.WeaponInfusionSlot", b =>
                {
                    b.HasBaseType("Gw2Gizmos.Data.EntityFramework.Entities.Items.ItemInfusionSlot");

                    b.Property<int>("WeaponDetailsId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("WeaponDetailsId");

                    b.ToTable("WeaponInfusionSlots");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Commerce.BuyListing", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Commerce.CommerceItemListing", "CommerceItemListing")
                        .WithMany("Buys")
                        .HasForeignKey("CommerceItemListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommerceItemListing");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Commerce.CommerceItemListing", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Commerce.SellListing", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Commerce.CommerceItemListing", "CommerceItemListing")
                        .WithMany("Sells")
                        .HasForeignKey("CommerceItemListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommerceItemListing");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ArmorDetails", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.Armor", "Armor")
                        .WithOne("Details")
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.ArmorDetails", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Armor");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ArmorStatChoice", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.ArmorDetails", "ArmorDetails")
                        .WithMany("StatChoices")
                        .HasForeignKey("ArmorDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArmorDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.BackItemDetails", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.BackItem", "BackItem")
                        .WithOne("Details")
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.BackItemDetails", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BackItem");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.BackItemStatChoice", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.BackItemDetails", "BackItemDetails")
                        .WithMany("StatChoices")
                        .HasForeignKey("BackItemDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BackItemDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.BagDetails", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.Bag", "Bag")
                        .WithOne("Details")
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.BagDetails", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bag");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ConsumableDetails", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.Consumable", "Consumable")
                        .WithOne("Details")
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.ConsumableDetails", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consumable");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ConsumableExtraRecipe", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.ConsumableDetails", "ConsumableDetails")
                        .WithMany("ExtraRecipes")
                        .HasForeignKey("ConsumableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsumableDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ConsumableSkin", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.ConsumableDetails", "ConsumableDetails")
                        .WithMany("Skins")
                        .HasForeignKey("ConsumableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsumableDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ContainerDetails", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.Container", "Container")
                        .WithOne("Details")
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.ContainerDetails", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.GatheringDetails", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.Gathering", "Gathering")
                        .WithOne("Details")
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.GatheringDetails", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gathering");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.InfixUpgradeAttribute", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.InfixUpgrade", "InfixUpgrade")
                        .WithMany("Attributes")
                        .HasForeignKey("InfixUpgradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InfixUpgrade");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.InfixUpgradeBuff", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.InfixUpgrade", "InfixUpgrade")
                        .WithOne("Buff")
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.InfixUpgradeBuff", "InfixUpgradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InfixUpgrade");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ItemFlag", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item", "Item")
                        .WithMany("Flags")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ItemGameType", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item", "Item")
                        .WithMany("GameTypes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ItemInfusionSlotFlag", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.ItemInfusionSlot", "InfusionSlot")
                        .WithMany("Flags")
                        .HasForeignKey("InfusionSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InfusionSlot");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ItemRestriction", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item", "Item")
                        .WithMany("Restrictions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.MiniPetDetails", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.MiniPet", "MiniPet")
                        .WithOne("Details")
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.MiniPetDetails", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MiniPet");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ToolDetails", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.Tool", "Tool")
                        .WithOne("Details")
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.ToolDetails", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.TrinketDetails", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.Trinket", "Trinket")
                        .WithOne("Details")
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.TrinketDetails", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trinket");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.TrinketStatChoice", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.TrinketDetails", "TrinketDetails")
                        .WithMany("StatChoices")
                        .HasForeignKey("TrinketDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrinketDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.UpgradeComponentDetails", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.UpgradeComponent", "UpgradeComponent")
                        .WithOne("Details")
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.UpgradeComponentDetails", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UpgradeComponent");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.WeaponDetails", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.Weapon", "Weapon")
                        .WithOne("Details")
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.WeaponDetails", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.WeaponStatChoice", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.WeaponDetails", "WeaponDetails")
                        .WithMany("StatChoices")
                        .HasForeignKey("WeaponDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeaponDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Recipes.RecipeDiscipline", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("Disciplines")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Recipes.RecipeFlag", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("Flags")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Recipes.RecipeIngredient", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Recipes.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ArmorInfixUpgrade", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.ArmorDetails", "ArmorDetails")
                        .WithOne("InfixUpgrade")
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.ArmorInfixUpgrade", "ArmorDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.InfixUpgrade", null)
                        .WithOne()
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.ArmorInfixUpgrade", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArmorDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.BackItemInfixUpgrade", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.BackItemDetails", "BackItemDetails")
                        .WithOne("InfixUpgrade")
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.BackItemInfixUpgrade", "BackItemDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.InfixUpgrade", null)
                        .WithOne()
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.BackItemInfixUpgrade", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BackItemDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.TrinketInfixUpgrade", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.InfixUpgrade", null)
                        .WithOne()
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.TrinketInfixUpgrade", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.TrinketDetails", "TrinketDetails")
                        .WithOne("InfixUpgrade")
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.TrinketInfixUpgrade", "TrinketDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrinketDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.UpgradeComponentInfixUpgrade", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.InfixUpgrade", null)
                        .WithOne()
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.UpgradeComponentInfixUpgrade", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.UpgradeComponentDetails", "UpgradeComponentDetails")
                        .WithOne("InfixUpgrade")
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.UpgradeComponentInfixUpgrade", "UpgradeComponentDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UpgradeComponentDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.WeaponInfixUpgrade", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.InfixUpgrade", null)
                        .WithOne()
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.WeaponInfixUpgrade", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.WeaponDetails", "WeaponDetails")
                        .WithOne("InfixUpgrade")
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.WeaponInfixUpgrade", "WeaponDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeaponDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Armor", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item", null)
                        .WithOne()
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.Armor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.BackItem", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item", null)
                        .WithOne()
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.BackItem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Bag", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item", null)
                        .WithOne()
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.Bag", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Consumable", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item", null)
                        .WithOne()
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.Consumable", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Container", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item", null)
                        .WithOne()
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.Container", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Gathering", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item", null)
                        .WithOne()
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.Gathering", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Gizmo", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item", null)
                        .WithOne()
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.Gizmo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.MiniPet", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item", null)
                        .WithOne()
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.MiniPet", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Tool", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item", null)
                        .WithOne()
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.Tool", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Trinket", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item", null)
                        .WithOne()
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.Trinket", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.UpgradeComponent", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item", null)
                        .WithOne()
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.UpgradeComponent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Weapon", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item", null)
                        .WithOne()
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.Weapon", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ArmorInfusionSlot", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.ArmorDetails", "ArmorDetails")
                        .WithMany("InfusionSlots")
                        .HasForeignKey("ArmorDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.ItemInfusionSlot", null)
                        .WithOne()
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.ArmorInfusionSlot", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArmorDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.BackItemInfusionSlot", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.BackItemDetails", "BackItemDetails")
                        .WithMany("InfusionSlots")
                        .HasForeignKey("BackItemDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.ItemInfusionSlot", null)
                        .WithOne()
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.BackItemInfusionSlot", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BackItemDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.TrinketInfusionSlot", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.ItemInfusionSlot", null)
                        .WithOne()
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.TrinketInfusionSlot", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.TrinketDetails", "TrinketDetails")
                        .WithMany("InfusionSlots")
                        .HasForeignKey("TrinketDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrinketDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.WeaponInfusionSlot", b =>
                {
                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.ItemInfusionSlot", null)
                        .WithOne()
                        .HasForeignKey("Gw2Gizmos.Data.EntityFramework.Entities.Items.WeaponInfusionSlot", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gw2Gizmos.Data.EntityFramework.Entities.Items.WeaponDetails", "WeaponDetails")
                        .WithMany("InfusionSlots")
                        .HasForeignKey("WeaponDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeaponDetails");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Commerce.CommerceItemListing", b =>
                {
                    b.Navigation("Buys");

                    b.Navigation("Sells");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ArmorDetails", b =>
                {
                    b.Navigation("InfixUpgrade");

                    b.Navigation("InfusionSlots");

                    b.Navigation("StatChoices");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.BackItemDetails", b =>
                {
                    b.Navigation("InfixUpgrade");

                    b.Navigation("InfusionSlots");

                    b.Navigation("StatChoices");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ConsumableDetails", b =>
                {
                    b.Navigation("ExtraRecipes");

                    b.Navigation("Skins");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.InfixUpgrade", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Buff");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Item", b =>
                {
                    b.Navigation("Flags");

                    b.Navigation("GameTypes");

                    b.Navigation("Restrictions");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.ItemInfusionSlot", b =>
                {
                    b.Navigation("Flags");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.TrinketDetails", b =>
                {
                    b.Navigation("InfixUpgrade");

                    b.Navigation("InfusionSlots");

                    b.Navigation("StatChoices");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.UpgradeComponentDetails", b =>
                {
                    b.Navigation("InfixUpgrade");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.WeaponDetails", b =>
                {
                    b.Navigation("InfixUpgrade");

                    b.Navigation("InfusionSlots");

                    b.Navigation("StatChoices");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Recipes.Recipe", b =>
                {
                    b.Navigation("Disciplines");

                    b.Navigation("Flags");

                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Armor", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.BackItem", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Bag", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Consumable", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Container", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Gathering", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.MiniPet", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Tool", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Trinket", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.UpgradeComponent", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });

            modelBuilder.Entity("Gw2Gizmos.Data.EntityFramework.Entities.Items.Weapon", b =>
                {
                    b.Navigation("Details")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
